version: '3.5'

services:
  backend:
    ports:
      - 8080:8080
    build: ./example-backend
    volumes:
      - ./example-backend:/mydir/backend
    environment: 
      - REDIS_HOST=redis-service
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
    container_name: back

  frontend:
    ports:
      - 5000:5000
    build: ./example-frontend
    volumes:
      - ./example-frontend:/mydir/frontend
    container_name: front

  redis-service:
    image: redis
    container_name: cache

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment: 
      - POSTGRES_PASSWORD=postgres
    container_name: db_redmine
    volumes:
      - pgdatabase:/mydir/data/postgresql/pgdatabase

  nginx-proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-proxy
    depends_on:
      - frontend
      - backend

volumes:
  pgdatabase: